# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Final/nexys4ddr.xdc

# IP: ip/div_16/div_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_16 || ORIG_REF_NAME==div_16} -quiet] -quiet
