# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Jeremy/6111-cv/final-test/final-test.srcs/sources_1/ip/div_16/div_16.xci
# IP: The module: 'div_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jeremy/6111-cv/final-test/final-test.srcs/sources_1/ip/div_16/div_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Jeremy/6111-cv/final-test/final-test.srcs/sources_1/ip/div_16/div_16.xci
# IP: The module: 'div_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jeremy/6111-cv/final-test/final-test.srcs/sources_1/ip/div_16/div_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
