# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Jeremy/6111-cv/final-test/final-test.srcs/sources_1/ip/hdmi/hdmi.xci
# IP: The module: 'hdmi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jeremy/6111-cv/final-test/final-test.srcs/sources_1/ip/hdmi/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Jeremy/6111-cv/final-test/final-test.srcs/sources_1/ip/hdmi/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Jeremy/6111-cv/final-test/final-test.srcs/sources_1/ip/hdmi/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Jeremy/6111-cv/final-test/final-test.srcs/sources_1/ip/hdmi/hdmi.xci
# IP: The module: 'hdmi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jeremy/6111-cv/final-test/final-test.srcs/sources_1/ip/hdmi/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Jeremy/6111-cv/final-test/final-test.srcs/sources_1/ip/hdmi/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Jeremy/6111-cv/final-test/final-test.srcs/sources_1/ip/hdmi/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
