# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Sreya Vangara/Documents/MIT/6.111/6.111/Final/final-test/final-test.srcs/sources_1/ip/centroid_div/centroid_div.xci
# IP: The module: 'centroid_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Sreya Vangara/Documents/MIT/6.111/6.111/Final/final-test/final-test.srcs/sources_1/ip/centroid_div/centroid_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'centroid_div'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Sreya Vangara/Documents/MIT/6.111/6.111/Final/final-test/final-test.srcs/sources_1/ip/centroid_div/centroid_div.xci
# IP: The module: 'centroid_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Sreya Vangara/Documents/MIT/6.111/6.111/Final/final-test/final-test.srcs/sources_1/ip/centroid_div/centroid_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'centroid_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
